title: SpectClient
description: A 1.12.2 anarchy client
logo: /src/main/resources/SpectClient Logo2.png
show_downloads: true
github:
  repository_url: https://github.com/SaberAspect/SpectClient
   jar_url: https://github.com/moomooooo/postman/releases/download/1.210/postman1.210.jar
cur_ver: 1.210

theme: jekyll-theme-cayman
