title: SpectClient
description: 1.12.2 anarchy client
logo: /src/main/resources/SpectClient Logo.png
show_downloads: true
github:
  repository_url: https://github.com/SaberAspect/SpectClient
cur_ver: 0.5.0
