title: SpectClient
description: A 1.12.2 anarchy client
logo: /src/main/resources/SpectClient Logo2.png
show_downloads: true
github:
  repository_url: https://github.com/SaberAspect/SpectClient
cur_ver: 0.5.0

theme: jekyll-theme-cayman
